repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.0
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
    # Run the formatter.
      - id: ruff-format

-   repo: local
    hooks:
      - id: pyright
        name: Pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
        verbose: true  # Show output only on failure

