name: Run Pyright

on:
  pull_request:
    branches:
      - "*"

jobs:
  pyright:
    name: Static Type Checking with Pyright
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (required for Pyright)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install Pyright globally
      - name: Install Pyright
        run: npm install -g pyright

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Install dependencies using uv
      - name: Install dependencies
        run: uv sync --all-extras

      # Run Pyright
      - name: Run Pyright
        run: uv run pyright
